version: 1
issues:
  serverID: beta_dev
  trackerName: JIRA
  regexp: (.+-[0-9]+)\s-\s(.+)
  keyGroupIndex: 1
  summaryGroupIndex: 2
  trackerUrl: https://www.jfrog.com/jira/browse/
  aggregate: true
  aggregationStatus: RELEASED
